apiVersion: v1
kind: Service
metadata:
  name: java-app-service
  labels:
    app: java-app
spec:
  selector:
    app: java-app
  ports:
    - name: http
      protocol: TCP
      port: 8200
      targetPort: 8200
  type: LoadBalancer