apiVersion: v1
kind: Service
metadata:
  name: java-app-service
  namespace: mututalfunds
  labels:
    app: java-app
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/actuator/prometheus"  # ← Tells Prometheus the path
    prometheus.io/port: "8200"
spec:
  selector:
    app: java-app
  ports:
    - name: http
      protocol: TCP
      port: 8200
      targetPort: 8200
  type: LoadBalancer